stages:
  - build
  - test

# Caching dependencies for faster installs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/
    - backend/node_modules/

# Anchors for reusable settings
.default-job: &default-job
  image: node:21
  before_script:
    - echo "Setting up..."

# Build Frontend
build_FE:
  <<: *default-job
  stage: build
  script:
    - echo "Building frontend..."
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/node_modules/ # Keep modules for tests
      - frontend/build/

# Build Backend
build_BE:
  <<: *default-job
  stage: build
  script:
    - echo "Building backend..."
    - cd backend
    - npm install
    - npm run build
  artifacts:
    paths:
      - backend/node_modules/ # Keep modules for tests
      - backend/dist/

# Test Frontend
test_FE:
  <<: *default-job
  stage: test
  dependencies:
