stages:
  - test
  - build

test_FE:
  stage: test   #Same stage run async
  image: node:21
  script:
    - cd frontend
    - npm install
    - npm test || echo "no frontend test found"

test_BE:
  stage: test
  image: node:21
  script:
    - cd backend
    - npm install
    - npm test || echo "no backend test found"


build_job:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
