stages:
  - test
  - build

test_FE:
  stage: test   #Same stage run async
  image: node:21
  script:
    - cd frontend
    - npm install
    - npm test || echo "no frontend test found"

test_BE:
  stage: test
  image: node:21
  script:
    - echo "Running tests..."
    - cd backend
    - npm install
    - npm test || echo "no backend test found"

build_FE:
  stage: build
  image: node:21
  script:
    - echo 'Building FE'
    - cd frontend
    - npm run build


build_BE:
  stage: build
  image: node:21
  script:
    - echo 'Building FE'B
    - cd backend
    - npm run build